- app/main-process/inklecate.js
> Linux: small fix for process.env.temp issue on Ubuntu

- README.md
> Add a Linux troubleshooting paragraph in README.md

- app/renderer/ace-ink-mode/ace-ink.js
TODO lines should be able to include punctuation inside their highlighting.
> Improved highlighting for TODO lines

- app/renderer/contextmenu.js
- app/renderer/controller.js
I basically added the menu entries from the sub menu under 'Edit' from the menu bar into a context menu.
> Adds a context menu as proposed in #73

- app/package.json
> Fixing weird fuzzaldrin-plus dependency bug

- app/package.json
- app/test/test.js
I have improved the test set up a bit and added some tests for testing behavior on application launch. 
To run the test you just have to run `npm test` or run the TEST_RELEASE_BUILD.command.
> Improved test setup + added tests for application launch

- app/test/test.js
Here I added a test case for a hello world game with regular text, choices and suppressed choice text.
> Test cases for hello world game

- app/main-process/appmenus.js
- app/main-process/main.js
- app/main-process/projectWindow.js
- app/renderer/inkProject.js
Hi!
We discussed on Discord that it'd be cool to have a word count option in Inky so here it is.  
I added a new entry in the *Story* menu.
It's counting words in the active file and recurse in included files.
I decided to filter out some obvious logic words:
* Lines beginning with
* `~`
* `VAR`
* `INCLUDE`
* Everything after a `->`
* Knots and stitch definitions
If anything needs to change, let me know.
Bests :heart:
> Word count

- app/main-process/appmenus.js
- app/main-process/projectWindow.js
- app/renderer/controller.js
- app/renderer/dark.css
- app/renderer/index.html
- app/renderer/inkTheme.css
- app/renderer/main.css
Suggested in #117, already had mine hacked so here it is.  
I added a menu to be able to choose between light and dark.
Missing feature: Inky does not save any configuration for now so it is switching back to the default (light) theme when closed.
> Dark theme

- app/renderer/dark.css
> Give issues popup a dark color scheme

- BUILD_FOR_WINDOWS.bat
It wasn't getting as far as running the actual packaging tool before.
Now it's as good as the other build scripts
> Fix up the windows build script

- app/export-for-web-template/index.html
- app/export-for-web-template/main.js
- app/export-for-web-template/style.css
> Added restart, save-load, and theme-switch features to web export

- app/main-process/aboutWindow.js
> hide about popup menubar

- app/export-for-web-template/index.html
- app/export-for-web-template/main.js
- app/export-for-web-template/style.css
- app/main-process/aboutWindow.js
- app/main-process/appmenus.js
- app/main-process/documentationWindow.js
- app/main-process/inklecate.js
- app/main-process/main.js
- app/renderer/about/about.html
- app/renderer/about/controller.js
- app/renderer/controller.js
- app/renderer/inkFile.js
- app/resources/Documentation/controller.js
- app/resources/Documentation/documentation.css
- app/resources/Documentation/documentationWindow.dark.css
- app/resources/Documentation/documentationWindowPrefab.html
I think this will fix #221 and and complete fix #117
> Implement dark mode for About and Docs windows

- app/export-for-web-template/main.js
- app/export-for-web-template/style.css
Fixes spacing in all CSS declarations.
Isolates .dark theme varations in CSS file for easier editing and as template for user theming.
Removes explicit usage of element names in selectors (e.g. p.choice) where .choice will always appear in `<p>` element.
Adds .byline selector for styling "# author: name" usage
Adds more documentation of tag selectors for #author and #end.
> Cleaning Web Export CSS

- app/main-process/appmenus.js
- app/main-process/main.js
- app/renderer/controller.js
Thought it would be convenient to have a font size menu in addition to the zoom menu. This will let users switch to a specific font size they want (within the given range) instead of zooming in and out a random number of times. *Zoom function is left untouched*
> Added zoom % menu

- app/main-process/appmenus.js
- app/main-process/projectWindow.js
- app/renderer/inkProject.js
This pull request adds an "Open recent" menu that allows the user to quickly re-open a recently opened or saved (main) file.
Closes #154.
> "Open recent" files menu

- app/package-lock.json
- app/renderer/ace-ink-mode/ace-ink.js
- app/renderer/acesrc/ace.js
Edited the ace-ink.js file to include inkFoldingRules. Now a fold toggle appears next to knot and stitch lines. Tested with the Intercept.
> Added Knot and Stitch Folding

- app/package-lock.json
Fixed a build-script breaking extra comma typo.
Installs and runs fine with the fix 👍
> Fix package-lock typo.

- app/main-process/appmenus.js
- app/main-process/main.js
- app/main-process/projectWindow.js
This pull request adds storage for the zoom and theme settings, which allows the user's selected settings to be loaded and applied on start up.
Closes #295 
Closes #342
> Theme and Zoom Storage

- app/main-process/inklecate.js
The following erroneous test case
```
-> init
== init
*
==choice1
* one
==choice2
* one
* 
```
triggers the following issue from the compiler.
```
RUNTIME ERROR: ran out of content. Do you need a '-> DONE' or '-> END'?
```
that was not matched by the existing regular expression (no line, no file), triggering an internal javascript error
In the absence of a line, the error is now matched and assigned to line 0.
Also added a fallback condition if a new error message from the compiler was to differ in the future.
> Fix internal javascript error with erroneous ink [known as the "cannot read property 5" alert]

- app/main-process/inkSnippets.js
missing some translation keys for snippets
> Missing some keys for translation 

- app/main-process/appmenus.js
Added shortcuts for "Story > Word count and more" and "Help > Show Documentation"
> Add more keyboard shortcuts

- app/export-for-web-template/main.js
**Functionality**
The added code performs the following actions:
1.	It checks the paragraphText variable to see if it is empty or consists only of whitespace characters.
2.	If paragraphText is empty, it uses the continue statement to skip any further processing for that paragraph.
3.	This enhancement helps in avoiding unnecessary processing of empty paragraphs, optimizing the code’s performance and readability.
**The results from this functionality:**
**Why is this change needed?**
This change is important because it ensures that the code doesn’t perform any unnecessary operations on empty paragraphs, which can improve the efficiency of the program and make the code more robust.
**Additional Information**
•	This change does not introduce any new external dependencies.
•	It has been tested …
> Update main.js with the ability to ignore empty paragraph.
