- app/export-for-web-template/main.js
On Firefox, scrollToButtom function reset to the top before scrolling down to button.
> Firefox scroll bug in Web Template

- app/renderer/main.css
There were too many nested divs with "overflow: scroll" on the player
pane, resulting in nested scrollbars. As a fix, I've removed this
property from the outermost #player div. I chose the outermost div for
parity's sake with the editor pane, which puts the scrollbars on the
inner content rather than the outer div.
Fixes issue #66.
> Remove Extra Scrollbars on Player Pane

- app/renderer/ace-ink-mode/ace-ink.js
- app/renderer/editorView.js
- app/renderer/inkCompleter.js
- app/renderer/inkFile.js
- app/renderer/inkFileSymbols.js
- app/renderer/inkProject.js
This pull request resolves #29 and #21 by implementing a custom completer for Inky. This replaces the `textCompleter` included by default in ACE, which was causing headaches for some people by suggesting every word from the text (including _punctuation_) as an auto-complete suggestion.
`inkCompleter` pulls flow-control symbol names from `InkFileSymbols`. `InkFileSymbols` has also been upgraded to parse out variable names, which are likewise used by the completer to provide suggestions. `inkCompleter` will pull suggestions from all files in the current project, not just the current file.
In addition to suggestions generated by `inkCompleter` based on the user's source files, `ace-ink-mode` now provides Ink keywords as suggested completions, which are then supplied to the auto-completer by …
> Add Custom Completer

- app/main-process/inklecate.js
- app/test/test.js
I noticed a small edge case in inky. If you have zero output before your set of choices, and no errors, TODOs won't show up. Example ink to demonstrate this:
```
-
* Rock
* Paper
* Scissors
TODO: Make this more interesting
```
This fixes it by making sure we flush errors to the UI once we encounter the prompt line. Since `sendAnyErrors` does nothing if we have no new errors, I don't believe there is any fear of losing errors flushed previously in the run.
> Display TODOs in edge case with zero content before choices

- app/renderer/inkProject.js
I stumbled upon #132 (which is actually a duplicate of #110) when coding for #133.
This only prevent Inky from freezing, and thus displays the inclusion error on the side.
> fix frontend infinite recursion when doing a circular inclusion

- app/renderer/ace-ink-mode/ace-ink.js
This regex tweak supports highlight skip for \#tag while retaining highlights for #tag as you would expect.
> Fix for \#tag highlighting

- app/renderer/ace-ink-mode/ace-ink.js
It was difficult to research exactly how to use Ace's highlighting system, but I believe this close to the proper way.
One improvement would be to move this escape sequence out to... someplace, but I have no idea where it should go. I tried putting it after the comment section, but no dice.
Someone who knows more than I do can make a more general purpose escape token, but this should work for this specific instance.
> \#tag fix attempt #2

- README.md
- app/main-process/ink/inklecate_linux
- app/main-process/inklecate.js
To assist those installing on Linux as covered in issue #145:
* Updated the README.md  (_simplified slightly by skipping the non-essential test steps included in issue instructions_)
* Added the convenience script `inklecate_linux` (with a corresponding change in  inklecate.js) so that step isn't required manually during installation
> Update Linux installation in README as per issue #145

- app/renderer/editorView.js
> Fixed ace marker highlights not being cleared when switching files

- app/package-lock.json
- app/package.json
This patch brings the `npm audit` from
```
found 37 vulnerabilities (1 moderate, 35 high, 1 critical)
```
to
```
found 1 moderate severity vulnerability
```
The last vulnerability is from [markdown-html](https://github.com/pwlmaciejewski/markdown-html) which depends on an [outdated version of marked](https://www.npmjs.com/advisories/812). As I believe it is only used to generate documentation and as this package is now archived and seems unmaintained (the last release and the last commit are 5 years old), I'd advise to look for an alternative.
> fix npm security audit

- app/renderer/playerView.js
Hello,
One minor change to not add duplicate `<hr/>` lines (this is prettier when choices do not print anything).
And one bigger change, that makes Inky behave MUCH better when story has huge list of choices (more than fits in screen):
- textBuffer.height can go shrink as well.
- Scroll top and down.
Previously, if a story had more choices than fits in the screen, then further on you would only see blank/white space after all the texts and choices, as textBuffer.height would never shrink and canvas would keep scrolling.
P. S. This is my first time working with node.js, so some things might be done not in the best way.
> Improve playerView behaviour

- app/main-process/appmenus.js
- app/main-process/main.js
- app/main-process/projectWindow.js
- app/renderer/controller.js
Creates new menu options under View, "Zoom (Increase)" and "Zoom (Decrease)". Clicking either calls ProjectWindow.zoom() which, in turn, sends a IPC message to the renderer window on the event 'zoom' with the amount to zoom.
In the renderer window (Controller.js), this message is watched for and the reaction is to look for and change the fontSize properties of the elements with the id "#editor" and that of the id "#player". (For whatever reason, using jQuery to get elements can sometimes removed the 'style' property.)
Using accelerator settings, the text size can be zoomed through CmdOrCtrl+K, to increase, or CmdOrCtrl+L to decrease. The preferred options would have been to use CmdOrCtrl+Plus and CmdOrCtrl+Minus, but Electron does not have "Minus" as an available key code. (See …
> Zoom support for Inky!

- app/renderer/ace-ink-mode/ace-ink.js
Another tweak to text highlighting.
`~` just needed a `^` to invalidate it when there's anything in front of it on the line.
`\{` and `\}` use a solution similar to the fix for `\#`
> Fix '~' and '\{' and '\}' highlighting

- .gitignore
- app/main-process/inklecate.js
Add logic to use TMPDIR environment variable for the temporary folder on linux and OSX platforms.
Note: I was able to test on linux both with the var set and unset.  However, I do not have a windows or OSX machine to test on; but I feel very confident that it will work as designed on both the other platforms.
> Respect tmpdir env var

- app/renderer/dark.css
Fixes #227 - TODO highlighting is now less bright and the TODO text is legible.
> Fixed formatting for dark mode TODO highlighting

- app/renderer/inkTheme.css
The current color of comments imported from Ace editor and logic color from inkTheme.css blend together with there subtle difference of green. This is a proposed auburn (reddish-brown) color to comments that contrast well from logic coloring and works with the current Light and Dark theme.
**Proposed Change (Light Theme):**
**Proposed Change (Dark Theme):**
For reference to current implementation.
**Current (Light Theme):**
**Current (Dark Theme):**
Another reason for proposing a different color all together is due to monitor color calibrations between various monitors these current shades of green can contrast well enough or seem identical.
Resolves #201
> Updated comment color to contrast logic color.

- app/renderer/inkFile.js
An attempt at preventing people from saving blank files in their Inky projects, by automatically including a placeholder comment at the beginning of every new file generated by Inky.
Quoting Furkle: " if you have blank files in your project and you save them, they disappear after you reopen, i'm not exactly sure why. the simple remediation is to never save a blank file and just put a comment, TODO, hello world, lorem, tag, whatever in it as a practice".
This is a common issue among new (and even experienced) users and results in many of them coming into discord asking why Inky ate their work. As a bug it's non-obvious and destructive (causing loss of work without an obvious reason).
https://github.com/inkle/inky/issues/197
https://discordapp.com/channels/329929050866843648/3299293903582658 …
> Hotfix - placeholder comments to prevent blank Include bug.

- app/export-for-web-template/style.css
Fix for https://github.com/inkle/ink/issues/525 (which should've been opened against inky, not ink)
> fade rule for immediate, not all, children of container

- app/renderer/dark.css
As mentioned in https://github.com/inkle/inky/issues/221 I thought the scrollbars shouldn't be blindingly bright whilst in dark mode.
> Darken scrollbars in dark mode

- app/package.json
A recent update to chokidar fixed an issue that caused high CPU usage on macOS when watching a directory that contains a large number of files, [as discussed here](https://github.com/paulmillr/chokidar/issues/447).
This might be the cause of issue #63
> Upgraded chokidar to fix high CPU usage

- app/renderer/dark.css
missed a few attributes that cause the corners where scrollbars met (like the preview pane) to be white while the rest of the scrollbar was dark.
> Fixed scrollbar corners being white in dark mode

- app/main-process/inklecate.js
Fix #196  which isn't Linux-exclusive like I thought it was, reading the issue now.
> Don't error if preview update is interrupted by window closure

- resources/Info.plist
Very small edit, just so Inky is for sure the default program to recommend and launch when opening .ink files on MacOS.
Resolves #258.
> Changed macOS handler rank

- app/renderer/inkProject.js
I did a tiny, likely unnecessary grammar fix on the word count alert while trying to figure out how the menu code works.
The code originally gives the following for 0, 1 and n > 1 words respectively:
"There is 0 word in this project."
"There is 1 word in this project."
"There is n words in this project."
Changed the alert so that it says:
"There are 0 words in this project."
"There is 1 word in this project."
"There are n words in this project."
> Changed grammar for word count alert

- app/export-for-web-template/main.js
Simple choice-to-tag-based external url support for the export template.
Requires that urls be escaped: `http:\/\/example.com`
Closes #265.
> Support # LINK and # LINKOPEN tags

- app/export-for-web-template/main.js
- app/export-for-web-template/style.css
Simple tag-based background image control for the export template.
Supports both local files and escaped image urls: `http:\/\/foo.com/bar.png`
Defaults to full size.
Closes #270
> Tag-based background images

- app/export-for-web-template/main.js
Simple tag-based audio control for the export template.
Separate channel for audio and looping audio, suitable for foreground and background events.
Supports both local files and escaped file urls: `http:\/\/foo.com/bar.mp3`
Closes #268
> Tag-based audio

- app/main-process/appmenus.js
When this feature was made Electron did not have "-" as an available key code so "L" and "K" were used as placeholders. Now that it is available we should use these new shortcut keys since they are more intuitive as they fall in line with every other application's zoom shortcut.
> Changed zoom out/in shortcut from Ctrl L/K to Ctrl -/=

- app/main-process/main.js
when the length of arg is 3, the indexOf function will return -1 == arg.length - 4
```javascript
// arg = "123", then
arg.indexOf(".ink") == arg.length - 4
```
> Fix an edge case when arg.length = 3

- app/renderer/dark.css
- app/renderer/main.css
This set of CSS changes does the following:
* Scrollbars are now thinner and eschew the thumb buttons, reducing visual clutter
* **Scrollbars now become dark when dark theme is enabled.**
* The file navigation pane and play preview no longer have unnecessary scrollbars enabled by default
> Improve editor scrollbar visuals

- app/renderer/inkProject.js
There is an bug on PC that doesn't allow error/warning jumps to go to sub-files (ink files in a sub-directory like `subfolder/test_file`). It just jumps to the correct line of whatever the current file is, since it can't find the right file.
The error is that on PC, the `file.relativePath()` returns a path with `\` instead of `/` which Inky expects, so when the relative path is checked, this fix swaps the `\` with `/`.
> Fix broken jumps to sub-files on PC

- app/main-process/appmenus.js
- app/main-process/main.js
- app/main-process/projectWindow.js
- app/renderer/controller.js
We get a lot of people asking about Find and Replace in the Ink discord, which indicates it's not a feature that's very obviously surfaced.
Find and Replace in Inky does, in fact, exist, and is provided by the Ace editor that Inky is built on. It's just not on a very intuitive keyboard shortcut - Ctrl+H - and at the moment there's no way to know this except through trial and error keyboard mashing or by googling "Ace editor keyboard shortcuts", which...also isn't intuitive.
What I wanted to do was hook up Find and Replace to the menu directly, but unfortunately, after a day or so of trying to do this, I couldn't find a way to do this that was achievable by me, and/or wouldn't break the next time we updated the ace editor library!
So, rather than introducing a lot of spaghetti for a …
> Keyboard shortcuts

- app/main-process/appmenus.js
- app/renderer/about/controller.js
- app/renderer/contrast.css
- app/renderer/controller.js
- app/renderer/dark.css
- app/renderer/focus.css
- app/renderer/index.html
In this PR we:
- Fixed some dark mode highlighting issues that were making it hard on the eye.
- Added new colorsafe/contrast and focus themes, for users with colorblindness and writers who want to focus on writing.
- Made small alterations to the theme-switching logic to make adding new themes easier. 
There were some complaints about the bright yellow highlight for loose end errors in dark mode.
(Above: Notable users raise issues with the bright yellow error highlights.
This has been replaced with a less glaring blue. The red has also been darkened for the dark mode error messages.
(Above: New darker error message colors for dark mode.)
A contrast mode has also been added - it is intended to be colorsafe and usable for most variants of weak and strong colorblindness. It has been tested …
> Dark mode fixes, new colorsafe and focus themes

- app/main-process/inklecate.js
Inky just stopped displaying errors (_No issues._) if number of error was too important.
Before
This was caused by inky trying to parse truncated output from inklecate.
Buffer and wait for EOL or } (end of Json) before processing inklecate's output
After
> [Bugfix] Large number of errors correctly displayed

- app/renderer/ace-ink-mode/ace-ink.js
I've noticed a few issues with Inky's highlighting rules, illustrated in the following passage.
```* A * /* * C *// A/*
*/
A * A * /* * C *// A/*
*/
* choice #tag
* choice 2 #tag
-
-
-
```
You can see a before and after of the changes here.
> Fixed ace highlight rules for choices, gathers, block comments

- build/createDocumentnavigation.js
Before this change links in the navigation of the offline documentation where broken, if they included a quote. (first entry: Advanced: a knottier "hello world")
> Fix links in documentation

- build/createDocumentnavigation.js
I added checks for commas and exclamation marks (these links are currently failing - e.g., "Health warning!" and "Sequences, cycles and other alternatives") and changed the current backtick behavior to accurately reflect how the character is altered by the markdown-html module (this was causing "Using `-> DONE `" to fail). I moved the punctuation checks before the dash checks in case removing a piece of punctuation creates a double dash.
> Fix broken documentation anchor links

- app/package-lock.json
- app/package.json
Insure latest version of inkjs (2.1.0) is used in web export.
Includes : 
- Fixed PRNG for shuffle of size 7
- Bugfixes on save/load
Only the runtime is exported in the webexport, not the compiler.
> Upgrade inkjs version

- app/main-process/appmenus.js
as described. 
Allow to assign short-cuts for custom ink submenus (with the notation per Electron Accelerators https://www.electronjs.org/docs/latest/api/accelerator)
"customInkSnippets": [
{
"name": "Heaven's Vault",
"submenu": [
{
"name": "Camera",
"ink": ">>> CAMERA: Wide shot"
"shortcut: "Alt+1"
},
> allow to assign shortcuts for the custom submenus

- app/export-for-web-template/main.js
I've seen a few people now get confused by the undocumented requirement for tags to be capitalised in order to work with the web player. This tweak automatically capitalises tags before comparison, so `#clear` will function identically to `#CLEAR`.
> Web player tag capitalisation fix

- app/export-for-web-template/main.js
To address a recurring issue caused by image tags (discussed in ink's issue [#674](https://github.com/inkle/ink/issues/674)) — where images loading into the `storyContainer` div could cause choices to be pushed down below its maximum height, often blocking progress — I've changed `continueStory()` to only briefly lock `storyContainer`'s height while removing choices, instead permanently locking it to the latest value of `contentBottomEdgeY()`.
I've noticed a similar issue with `scrollDown()`, which can't calculate the right targe until the images have loaded in. Unfortunately, this commit does nothing to address that, but it should still help prevent users from having their stories break when they use an image tag.
> Updated continueStory to fix issue with image tags and scrolling

- app/export-for-web-template/main.js
- app/export-for-web-template/style.css
The [`prefers-reduced-motion` media query](https://css-tricks.com/introduction-reduced-motion-media-query/) allows users to specify an accessibility setting for less animation.
The purpose of this PR is to respect this setting in web export.
- Scrolling: Smooth scrolling triggers seasickness, so disable it. Instant scrolling is usually preferred but would be disorienting in the context of Ink games. Instead, let the user scroll at their own pace.
- Fade-in: A row of flashing paragraphs can also be a vestibular trigger. Show all the paragraphs at once.
- Colour transitions: Not necessary for seasickness reduction, but exposes current app state more clearly.
See also: [PR for inkjs](https://github.com/y-lohse/inkjs/pull/966) with similar changes.
> Disable web animations when the user prefers reduced motion

- README.md
Another option would be to use the link https://github.com/inkle/ink-unity-integration/releases instead of the link to the Unity Asset Store.
> Update unity asset store plugin link

- app/renderer/main.css
Removed Verdana font so previewer uses the system font first, which has support for all diacritics as far as I've been able to tell between iOS and Windows.
See this thread for additional details: https://github.com/inkle/inky/issues/444
> Resolved issue with certain diacritics
